package rex

import (
	"bytes"
	b64 "encoding/base64"
	"testing"
)

func TestDecodingHeader(t *testing.T) {

	b, err := b64.StdEncoding.DecodeString(rexBuffer)
	if err != nil {
		panic(err)
	}
	r := bytes.NewReader(b)

	d := NewDecoder(r)
	header, rex, err := d.Decode()

	if err != nil {
		t.Fatalf("TEST ERROR: %v", err)
	}
	if rex == nil {
		t.Fatalf("REX file is nil")
	}

	if header.SizeBytes != 276 {
		t.Fatalf("TotalSize does not match")
	}
}

// Base64 encoded test REX file
// Generated by base64 mesh.rex
const rexBuffer = `
UkVYMQEAAAAAAAIAVgAUAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAACQPAAAEAEVQU0cAAAAAAAAAAAAAAAADAAEAsAAAAAEAAAAAAAAAAAAAAAMAAAAAAAAA
AAAAAAAAAAABAAAAgAAAAKQAAACkAAAApAAAAKQAAAAAAAAAAAAAAAQAdGVzdAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAA/AACAPwAAAAAAAAAAAQAAAAIAAAAFAAEARAAA
AAAAAAAAAAAAAACAPwAAAAAAAAAA/////////38AAIA/AAAAAAAAAAD/////////fwAAgD8AAAAA
AAAAAP////////9/AAAAAAAAgD8=
`
